config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # read all the tasks
  get '/tasks', to: 'tasks#index'
  # read one task
  get '/tasks/new', to: 'tasks#new' # display the form
  # create a task
  post '/tasks', to: 'tasks#create'

  get '/tasks/:id', to: 'tasks#show', as: :task

  # update a task
  get '/tasks/:id/edit', to: 'tasks#edit'
  patch '/tasks/:id', to: 'tasks#update'
  # delete a task
  delete '/tasks/:id', to: 'tasks#destroy', as: :delete
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    @tasks = Task.all # display all tasks
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to tasks_path
  end

  def show
    @task = Task.find(params[:id])
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<div class="container">
  <h1>Edit task</h1>
  <%= form_for @task do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :details %>
    <%= f.text_field :details %>
  </div>
  <div>
    <%= f.submit %>
  </div>
  <div>
    <%= link_to "Back to list", tasks_path %>
  </div>
  <% end %>
</div>

app/views/tasks/index.html.erb
<div class="container">
  <h1>My tasks</h1>
  <ul>
    <% @tasks.each do |task| %>
      <% if task.completed? %>
        <div>
          <i class="far fa-check-square"></i>
          <%= link_to task.title, task_path(task) %>
          <%= link_to task_path(task), method: :delete, data: { confirm: 'Are you sure?' } do %>
        <i class="far fa-trash-alt"></i>
        <% end %>
        </div>
      <% else %>
        <div>
          <i class="far fa-square"></i>
          <%= link_to task.title, task_path(task) %>
          <%= link_to task_path(task), method: :delete, data: { confirm: 'Are you sure?' } do %>
          <i class="far fa-trash-alt"></i>
          <% end %>
        </div>
      <% end %>
    <% end %>
  </ul>
      <i class="fas fa-plus"></i>
      <%= link_to "Add a new task", tasks_new_path %>
</div>

app/views/tasks/new.html.erb
<%= form_for @task do |f| %>
<div class="form-group">
  <%= f.label :title %>
  <%= f.text_field :title, class: 'form-control' %>
</div>
<div class="form-group">
  <%= f.label :details %>
  <%= f.text_field :details, class: 'form-control' %>
</div>
<div>
  <div class="input"><%= f.submit class: 'btn btn-dark' %></div>
</div>
<div>
  <%= link_to "Back to list", tasks_path %>
</div>
<% end %>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>

<div>
<%= @task.details %>
  <% if @task.completed? %>
      <div><i class="far fa-check-square"></i><span> This task is completed</span></div>
  <% else %>
      <div><i class="far fa-square"></i><span> This task is not completed yet</span></div>
  <% end %>
</div>

<div>
  <%= link_to "Back to list", tasks_path %>
</div>